### ISSUE TITLE
Mistake on steps

### ISSUE THREAD

**Issue by wimel** [sentinel-official/docs#2]
On steps for [gentx](https://github.com/sentinel-official/docs/blob/master/guides/testnets/turing-3/GENTX.md#gentx) on step 4 (`cp ${HOME}/testnets/turing-3/genesis.json ${HOME}/.sentinel-hubd/config/`)  but (I think) the correct is:
```
cp ${HOME}/testnets-1/turing-3/genesis.json ${HOME}/.sentinel-hubd/config/
```
And same for the step `8` I think the correct is:
```
cp ${HOME}/.sentinel-hubd/config/gentx/gentx-*.json ${HOME}/testnets-1/turing-3/gentx/
```

**Comment by ironman0x7b2** [comment]
The path actually depends on the forked repository name.
I feel, we should mention the output folder name for the git clone.

**Comment by wimel** [comment]
ohh, I see sorry!!
